INSERT INTO users (name, age) VALUES ("Bryn", 27);
INSERT INTO users (name, age) VALUES ("Grace", 29);
INSERT INTO users (name, age) VALUES ("Trish", 28);
INSERT INTO users (name, age) VALUES ("Brooke", 18);
INSERT INTO users (name, age) VALUES ("Paige", 24);
INSERT INTO users (name, age) VALUES ("Kate", 27);
INSERT INTO users (name, age) VALUES ("Maddie", 27);
INSERT INTO users (name, age) VALUES ("Jimmy", 28);
INSERT INTO users (name, age) VALUES ("Justyn", 17);
INSERT INTO users (name, age) VALUES ("Judy", 63);
INSERT INTO users (name, age) VALUES ("Chase", 29);
INSERT INTO users (name, age) VALUES ("Monica", 30);
INSERT INTO users (name, age) VALUES ("Val", 24);
INSERT INTO users (name, age) VALUES ("Lyndsey", 25);
INSERT INTO users (name, age) VALUES ("Kevin", 30);
INSERT INTO users (name, age) VALUES ("Michael", 28);
INSERT INTO users (name, age) VALUES ("Ivan", 26);
INSERT INTO users (name, age) VALUES ("Alexa", 30);
INSERT INTO users (name, age) VALUES ("Chelsea", 30);
INSERT INTO users (name, age) VALUES ("Tori", 30);


INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj1", "Cat1", 500, "May 1", "May 31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj2", "Cat2", 5000, "March 20", "March 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj3", "Cat3", 100, "April 1", "May 31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj4", "Cat1", 400, "May 1", "June 1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj5", "Cat3", 6000, "March 19", "March 26");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj6", "Cat2", 1000, "March 20", "March 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj7", "Cat1", 2500, "May 1", "May 31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj8", "Cat2", 2000, "March 20", "March 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj9", "Cat2", 2500, "April 15", "April 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Proj10", "Cat2", 500, "April 1", "April 20");

INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 19, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 12, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 8, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 13, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 14, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 20, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 16, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 15, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 5, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 9, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 8, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 15, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 16, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 11, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 11, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 16, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 9, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 9);
